apiVersion: v1
kind: ConfigMap
metadata: 
  name: web-demo-html
  namepscape: web-demo
data: 
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes Lab</title>
    </head>
    <body>
      <h1>Hello from Kubernetes!</h1>
      <h2>My first GitOps application</h2>
      <p>Deployed using:</p>
      <ul>
        <li>Kubernetes</li>
        <li>Argo CD</li>
        <li>NGINX Ingress Controller</li>
        <li>GitHub</li>
      </ul>
    </body>
    </html>